import { useSnackbar } from '@/composables/useSnackbar'

export const handleSupabaseRequest = async (request) => {
  const { showSnackBar } = useSnackbar() 

  try {
    const { data, error } = await request()
    if (error) {
      showSnackBar("エラーが発生しました")
      throw error
    }
    return data
  } catch (e) {
    console.error("Supabase Error:", e)
  }
}

// 業種一覧を返す
export const getIndustryOptions = () => [
  { code: '01', name: '01　農業' },
  { code: '02', name: '02　林業' },
  { code: '03', name: '03　漁業（水産養殖業を除く）' },
  { code: '04', name: '04　水産養殖業' },
  { code: '05', name: '05　鉱業，採石業，砂利採取業' },
  { code: '06', name: '06　総合工事業' },
  { code: '07', name: '07　職別工事業(設備工事業を除く)' },
  { code: '08', name: '08　設備工事業' },
  { code: '09', name: '09　食料品製造業' },
  { code: '10', name: '10　飲料・たばこ・飼料製造業' },
  { code: '11', name: '11　繊維工業' },
  { code: '12', name: '12　木材・木製品製造業（家具を除く）' },
  { code: '13', name: '13　家具・装備品製造業' },
  { code: '14', name: '14　パルプ・紙・紙加工品製造業' },
  { code: '15', name: '15　印刷・同関連業' },
  { code: '16', name: '16　化学工業' },
  { code: '17', name: '17　石油製品・石炭製品製造業' },
  { code: '18', name: '18　プラスチック製品製造業（別掲を除く）' },
  { code: '19', name: '19　ゴム製品製造業※' },
  { code: '20', name: '20　なめし革・同製品・毛皮製造業' },
  { code: '21', name: '21　窯業・土石製品製造業' },
  { code: '22', name: '22　鉄鋼業' },
  { code: '23', name: '23　非鉄金属製造業' },
  { code: '24', name: '24　金属製品製造業' },
  { code: '25', name: '25　はん用機械器具製造業' },
  { code: '26', name: '26　生産用機械器具製造業' },
  { code: '27', name: '27　業務用機械器具製造業' },
  { code: '28', name: '28　電子部品・デバイス・電子回路製造業' },
  { code: '29', name: '29　電気機械器具製造業' },
  { code: '30', name: '30　情報通信機械器具製造業' },
  { code: '31', name: '31　輸送用機械器具製造業' },
  { code: '32', name: '32　その他の製造業' },
  { code: '33', name: '33　電気業' },
  { code: '34', name: '34　ガス業' },
  { code: '35', name: '35　熱供給業' },
  { code: '36', name: '36　水道業' },
  { code: '37', name: '37　通信業' },
  { code: '38', name: '38　放送業' },
  { code: '39', name: '39　情報サービス業' },
  { code: '40', name: '40　インターネット附随サービス業' },
  { code: '41', name: '41　映像・音声・文字情報制作業' },
  { code: '42', name: '42　鉄道業' },
  { code: '43', name: '43　道路旅客運送業' },
  { code: '44', name: '44　道路貨物運送業' },
  { code: '45', name: '45　水運業' },
  { code: '46', name: '46　航空運輸業' },
  { code: '47', name: '47　倉庫業' },
  { code: '48', name: '48　運輸に附帯するサービス業' },
  { code: '49', name: '49　郵便業（信書便事業を含む）' },
  { code: '50', name: '50　各種商品卸売業' },
  { code: '51', name: '51　繊維・衣服等卸売業' },
  { code: '52', name: '52　飲食料品卸売業' },
  { code: '53', name: '53　建築材料，鉱物・金属材料等卸売業' },
  { code: '54', name: '54　機械器具卸売業' },
  { code: '55', name: '55　その他の卸売業' },
  { code: '56', name: '56　各種商品小売業' },
  { code: '57', name: '57　織物・衣服・身の回り品小売業' },
  { code: '58', name: '58　飲食料品小売業' },
  { code: '59', name: '59　機械器具小売業' },
  { code: '60', name: '60　その他の小売業' },
  { code: '61', name: '61　無店舗小売業' },
  { code: '62', name: '62　銀行業' },
  { code: '63', name: '63　協同組織金融業' },
  { code: '64', name: '64　貸金業，クレジットカード業等非預金信用機関' },
  { code: '65', name: '65　金融商品取引業，商品先物取引業' },
  { code: '66', name: '66　補助的金融業等' },
  { code: '67', name: '67　保険業（保険媒介代理業，保険サービス業を含む）' },
  { code: '68', name: '68　不動産取引業' },
  { code: '69', name: '69　不動産賃貸業・管理業' },
  { code: '70', name: '70　物品賃貸業' },
  { code: '71', name: '71　学術・開発研究機関' },
  { code: '72', name: '72　専門サービス業（他に分類されないもの）' },
  { code: '73', name: '73　広告業' },
  { code: '74', name: '74　技術サービス業（他に分類されないもの）' },
  { code: '75', name: '75　宿泊業' },
  { code: '76', name: '76　飲食店' },
  { code: '77', name: '77　持ち帰り・配達飲食サービス業' },
  { code: '78', name: '78　洗濯・理容・美容・浴場業' },
  { code: '79', name: '79　その他の生活関連サービス業' },
  { code: '80', name: '80　娯楽業' },
  { code: '81', name: '81　学校教育' },
  { code: '82', name: '82　その他の教育，学習支援業' },
  { code: '83', name: '83　医療業' },
  { code: '84', name: '84　保健衛生' },
  { code: '85', name: '85　社会保険・社会福祉・介護事業' },
  { code: '86', name: '86　郵便局' },
  { code: '87', name: '87　協同組合（他に分類されないもの）' },
  { code: '88', name: '88　廃棄物処理業' },
  { code: '89', name: '89　自動車整備業' },
  { code: '90', name: '90　機械等修理業（別掲を除く）' },
  { code: '91', name: '91　職業紹介・労働者派遣業' },
  { code: '92', name: '92　その他の事業サービス業' },
  { code: '93', name: '93　政治・経済・文化団体' },
  { code: '94', name: '94　宗教' },
  { code: '95', name: '95　その他のサービス業' },
  { code: '96', name: '96　外国公務' },
  { code: '97', name: '97　国家公務' },
  { code: '98', name: '98　地方公務' },
  { code: '99', name: '99　分類不能の産業' }
];

